name: ci / cd

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  SCRETE_ACCESS: ${{ vars.SCRETE_ACCESS }}
  SCRETE_REFRESH: ${{ vars.SCRETE_REFRESH }}
  PORT: ${{ vars.PORT }}
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install and test
        run: |
          npm install
          npm test

  deployment:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd chat-app-server/
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo ln -s "$NVM_DIR/versions/node/v17.9.1/bin/node" "/usr/local/bin/node"
            sudo ln -s "$NVM_DIR/versions/node/v17.9.1/bin/npm" "/usr/local/bin/npm" 
            git pull origin master
            npm run build:prod
            pm2 restart dist/bundle.js --update-env
            echo "build compleleted✅"
