name: ci / cd

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  SCRETE_ACCESS: ${{ vars.SCRETE_ACCESS }}
  SCRETE_REFRESH: ${{ vars.SCRETE_REFRESH }}
  PORT: ${{ vars.PORT }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install and test
        run: |
          npm install
          npm test

  deployment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd chat-app-server/
            ls
